# This file is auto-generated by hatch-vcs, do not edit manually
# The placeholder below is used in the working tree; when the package is
# installed, try to obtain the real version from importlib.metadata and
# fall back to the placeholder only if the distribution is not installed.
try:
    from importlib import metadata as _metadata
    from importlib.metadata import PackageNotFoundError as _PackageNotFoundError
except ImportError:
    _metadata = None
    _PackageNotFoundError = Exception

_DIST_NAME = "bib-lookup"

if _metadata is not None:
    try:
        __version__ = _metadata.version(_DIST_NAME)
    except _PackageNotFoundError:
        __version__ = "0.0.0"  # placeholder, overwritten at build time
else:
    __version__ = "0.0.0"  # placeholder, overwritten at build time
