# This file is auto-generated by hatch-vcs, do not edit manually
# The placeholder below is used in the working tree; when the package is
# installed, try to obtain the real version from importlib.metadata and
# fall back to the placeholder only if the distribution is not installed.
try:
    from importlib import metadata as _metadata
except Exception:
    _metadata = None

_PACKAGE_NAME = (__package__ or __name__).split(".")[0]

if _metadata is not None:
    try:
        __version__ = _metadata.version(_PACKAGE_NAME)
    except Exception:
        __version__ = "0.0.0"  # placeholder, overwritten at build time
else:
    __version__ = "0.0.0"  # placeholder, overwritten at build time
